<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>layers_demo</name>
  <version>0.0.1</version>
  <description>rclcpp / rcl / rmw / DDS 四层分层演示代码（面试准备用）</description>
  <maintainer email="you@example.com">you</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>rcl</depend>
  <depend>rmw</depend>
  <depend>std_msgs</depend>
  <depend>rosidl_typesupport_c</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
